name: Docker Image

on:
  push:
    branches: [develop, gfkari]
    # tags:
    #   - v*
  pull_request:
    branches: [develop]

env:
  REPO_NAME: szurubooru
  CLIENT_IMAGE_NAME: client
  SERVER_IMAGE_NAME: server

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and Push the Client image
        uses: docker/build-push-action@v2
        with:
          context: ./server
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}/${{ env.CLIENT_IMAGE_NAME }}:latest

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Build and Push the Server image
        uses: docker/build-push-action@v2
        with:
          context: ./client
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}/${{ env.SERVER_IMAGE_NAME }}:${{ steps.extract_branch.outputs.branch }}
