name: Docker Image

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  IMAGE_NAME: server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          cd server/
          docker build . --file Dockerfile --tag $IMAGE_NAME:$(date +%s)
